export const GET_ITEMS_CONTACT = 'GET_ITEMS_CONTACT';
export const GET_ITEM_CONTACT = 'GET_ITEM_CONTACT';
export const ADD_NEW_ITEM_CONTACT = 'ADD_NEW_ITEM_CONTACT';
export const UPDATE_EXISTING_ITEM_CONTACT = 'UPDATE_EXISTING_ITEM_CONTACT';
export const DELETE_ITEM_CONTACT = 'DELETE_ITEM_CONTACT';

